---
- name: Smoketest the 3 tier OSP Install
  hosts: jumpbox
  tasks:

  - name: Gather facts
    include_role: 
      name: osp-facts

- name: Smoketest the frontend.
  hosts: frontends
  tasks:

  - name: Grab page content if it exists
    uri:
      url: "http://{{ ansible_host }}"
      return_content: yes
    register: webpage

  - name: Fail if Ansible Deployed Tomcat is not in the page content
    fail:
    when: "'Ansible Deployed Tomcat' not in webpage.content"